version: "3.6"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front
    ports:
      - "80:80"

  front:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    volumes:
      - ./app:/app
      - /app/node_modules
      - /app/.next
    expose:
      - "3000"
